### ISSUE TITLE
Remove Google dependencies

### ISSUE THREAD

**Issue by gary-host-laptop** [Kimtaro/jisho.org#6]
Google is a threat to an open internet and it is the biggest company that profits from data collection and surveillance mechanisms, and a lot of the products/services they offer are proprietary spyware. It would be incredible and a huge step in favour of a more private, open and decentralized network if projects would stop relying on such a harmful entity.

Either hosting the dependencies locally, or using a more private and open source alternative would be fine, I know there are a lot of good alternative out there, you can probably find the one that suits you best over AlternativeTo.

----

I also would like to ask if this is the source code of the current version of Jisho or if this is the source code of the classic version, because the readme and the repository's description say different things.

**Comment by Kimtaro** [comment]
I agree completely. I am not a fan of Google's products and I am looking into alternatives. Unfortunately because of Jisho's scale alternatives are either prohibitively expensive or hard to set up. But I am hopeful that I can find a good alternative soon.

This repo is for classic.jisho.org. The source code for jisho.org is not public, except for targeted pieces that can be useful to others, like https://github.com/kimtaro/ve

**Comment by gary-host-laptop** [comment]
If you let me know of some requirements I could help you find a good replacement, I know a friend who uses GoatCounter on his website and it seems to work okay I guess, and I think the people over at PrivacyTools.io use Matomo, and that's where my knowledge about other services ends, but I can ask around.

>This repo is for classic.jisho.org. The source code for jisho.org is not public, except for targeted pieces that can be useful to others, like https://github.com/kimtaro/ve

Would it be too much to ask if we had some empty repo with only a readme to fill in issues? Yesterday I found out that Gojira has a kanji form which is not on the web site and I was wondering if one could submit these. 

This is the kanji (呉爾羅) which it seems to be ateji, but both [this](https://learnjapanesepod.com/what-is-the-kanji-for-godzilla/) website and the [Wikizilla](https://wikizilla.org/wiki/Godzilla#Name) seem to agree on it, I'm sure there must be another source on Japanese but I can't find it.

**Comment by Kimtaro** [comment]
@LongJohn-Silver Thanks, I was unaware of GoatCounter, I'll look into it. I've previously looked into Matomo and a couple of others. My best option is probably self-hosting. Right now my focus is on a large rewrite of the database layer, but I hope to look into this once that's done.

There's detailed instructions on how to report issues/new data to the right projects on our FAQ page: https://jisho.org/faq. It's also fine to email me at jisho.org@gmail.com. For 呉爾羅 your best option is probably to submit an amendment to JMdict, following the instructions under "Errors in a word" on the FAQ. If they accept it into JMdict it will show up on Jisho as well.

I'm reluctant to create an empty GitHub project as it would just be another channel I can be slow to respond to :)

**Comment by Kimtaro** [comment]
@LongJohn-Silver Just wanted to let you know that I have finally removed Google Analytics from Jisho. I have not yet added alternative tracking, but will be looking more into GoatCounter and other privacy aware alternatives over the next month.

**Comment by gary-host-laptop** [comment]
Thanks a lot for caring about users' privacy, @Kimtaro!

Hope one day Jisho can be libre/free for everyone to study!

**Comment by gary-host-laptop** [comment]
By the way, I found this, which may be useful.

https://nocookieanalytics.com/

**Comment by Kimtaro** [comment]
@LongJohn-Silver Interesting, I'll have a look. Thanks!
